//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelpers.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee3
    {
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string JOB_TITLE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    }
}
